# Generated by Django 3.2.8 on 2021-10-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='tarix',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.AddField(
            model_name='blog',
            name='soyad',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
